# cmake/scripts/bin2h.cmake
#
# TheSuperHackers @build githubawn 15/07/2026 Generic binary-file-to-C-header
# converter, run via `cmake -P` from a custom command. Used by
# cmake/citro3d.cmake's ggc_compile_pica_shader to embed compiled PICA200
# .shbin files (picasso has no built-in bin2c, unlike bgfx's shaderc
# --bin2c). Invoke with -DINPUT=<path> -DOUTPUT=<path> -DVARNAME=<name>.
#
# Emits `static const unsigned char <VARNAME>[] = {...};` and
# `static const unsigned int <VARNAME>_size = <N>;` in a single header.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VARNAME)
    message(FATAL_ERROR "bin2h.cmake requires -DINPUT=, -DOUTPUT=, -DVARNAME=")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexLen)
math(EXPR _byteCount "${_hexLen} / 2")

# Turn "deadbeef..." into "0xde, 0xad, 0xbe, 0xef, ..." in one regex pass
# rather than a per-byte loop (thousands of CMake function calls for a
# shader-sized file would be painfully slow).
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " _bytes "${_hex}")

file(WRITE "${OUTPUT}"
"// Auto-generated by cmake/scripts/bin2h.cmake from ${INPUT}. Do not edit.
#pragma once
static const unsigned char ${VARNAME}[] = {
${_bytes}
};
static const unsigned int ${VARNAME}_size = ${_byteCount}u;
")
