/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
*/

#if defined(SAGE_USE_SDL3)

// TheSuperHackers @build bobtista 29/04/2026 Pull in the Win compat shim
// before any engine header so AsciiString.h's inline _stricmp resolves
// (compat/win32_shims/windows.h maps it to strcasecmp on non-Win).
#include <windows.h>

#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#include <emscripten/html5.h>
// Defined in Core/GameEngine/Source/GameNetwork/udp.cpp: opens the WebSocket the LAN
// transport tunnels through. UDP::Bind opens it too, but the handshake is asynchronous, so
// connecting at startup gives it time to be ready before LAN discovery starts announcing.
extern "C" void ggc_ws_connect(void);
#endif

#include <SDL3/SDL.h>
#if defined(__APPLE__)
#include <SDL3/SDL_metal.h>
#endif
#include <cstdio>
#include <cstdlib>
#include <string>

// TheSuperHackers @info bobtista 30/04/2026 Release builds strip
// WWDEBUG_SAY, so during macOS bring-up we emit a small set of stderr
// breadcrumbs so we can see where init reaches even when the window
// never comes up. Set GGC_TRACE=1 to enable.
#define GGC_TRACE(fmt, ...) do { \
    if (GgcFlags::Enabled(GgcFlag_Trace)) { \
        std::fprintf(stderr, "[ggc] " fmt "\n", ##__VA_ARGS__); \
        std::fflush(stderr); \
    } \
} while (0)

#include "Common/CommandLine.h"
#include "Common/Debug.h"
#include "Common/GameEngine.h"
#include "Common/GameMemory.h"
#include "Common/GlobalData.h"
#include "Common/version.h"
#include "GameClient/ClientInstance.h"
#include "GgcRuntimeFlags.h"
#include "SDL3GameEngine.h"
// Version constants generated by cmake at configure time.
#include "BuildVersion.h"
#include "GeneratedVersion.h"

namespace
{
	const char * const kWindowTitle = "Command & Conquer Generals Zero Hour";
	const int kDefaultWindowWidth = 800;
	const int kDefaultWindowHeight = 600;
	const int kMinWindowWidth = kDefaultWindowWidth;
	const int kMinWindowHeight = kDefaultWindowHeight;
}

#if !defined(_WIN32)
// TheSuperHackers @build bobtista 07/06/2026 On Windows the CRT already declares and populates
// __argc/__argv (stdlib.h) before main() runs (see /ENTRY:mainCRTStartup); only POSIX needs these.
int __argc = 0;
char **__argv = NULL;
#endif

// TheSuperHackers @bugfix bobtista 30/04/2026 Backing storage for the
// compat shim's GetCommandLineA(). Populated in main() before any
// CommandLine::parse* call so the engine sees the real arg vector
// joined into a single Win32-style command-line string.
const char *g_compatCommandLine = "";
static std::string s_compatCommandLineStorage;

// TheSuperHackers @build bobtista 29/04/2026 Globals normally provided by the
// Win-side WinMain.cpp.
const char *g_strFile = "data/Generals.str";
const char *g_csfFile = "data/%s/Generals.csf";
// TheSuperHackers @build bobtista 09/06/2026 Debug.cpp references gAppPrefix from inside
// DEBUG_LOGGING-gated code; WinMain.cpp defines it on Win, so provide it here so a logging
// build of the SDL3 entry point links.
const char *gAppPrefix = "";

// Stack-dump shims. The Win build provides these in core_debug; the engine
// references them from RTS_DEBUG / IG_DEBUG_STACKTRACE-gated code so just
// give them weak no-ops on non-Win.
#include "Common/StackDump.h"
AsciiString g_LastErrorDump;
void FillStackAddresses(void ** /*addresses*/, unsigned int /*count*/, unsigned int /*skip*/) {}
void StackDumpFromAddresses(void ** /*addresses*/, unsigned int /*count*/, void (* /*cb*/)(const char *)) {}
void StackDump(void (* /*cb*/)(const char *)) {}
void StackDumpFromContext(unsigned long /*eip*/, unsigned long /*esp*/, unsigned long /*ebp*/, void (* /*cb*/)(const char *)) {}
void GetFunctionDetails(void * /*p*/, char * /*name*/, char * /*filename*/, unsigned int * /*line*/, unsigned int * /*addr*/) {}
void DumpExceptionInfo(unsigned int /*u*/, EXCEPTION_POINTERS * /*e*/) {}

// OS busy-state UI is Win-only.
void OSDisplaySetBusyState(Bool /*busyDisplay*/, Bool /*busySystem*/) {}

SDL_Window *TheSDL3Window = NULL;
// TheSuperHackers @build bobtista 07/06/2026 Define with the same HWND type every consumer
// extern-declares it as. On macOS HWND is a void* shim so this is unchanged; on Windows HWND is
// the real type, and defining it as void* here left the symbol unresolved at link.
HWND ApplicationHWnd = NULL;
#if defined(_WIN32)
// TheSuperHackers @build bobtista 13/06/2026 ATL's _Module.Init (GameEngine ctor, Win-only) needs
// the real module handle. WinMain.cpp supplies this on the non-SDL3 Win build; the SDL3 entry point
// must define and populate it too (set in main() via GetModuleHandle), else the Win SDL3 link fails.
HINSTANCE ApplicationHInstance = NULL;
#endif
// TheSuperHackers @bugfix bobtista 30/04/2026 macOS-only: keep the
// SDL_Metal view alive for the lifetime of the bgfx renderer, and
// publish its CAMetalLayer pointer here so BgfxBackend's
// GetNativeWindowHandle can hand it to bgfx as platformData.nwh
// instead of an NSWindow. Passing the NSWindow lets bgfx try to
// install its own CAMetalLayer on the contentView, which fights with
// the layer SDL3 already created and trips the Apple AGX driver
// during pipeline-state compile.
#if defined(__APPLE__)
SDL_MetalView TheSDL3MetalView = NULL;
void *TheSDL3MetalLayer = NULL;
#endif

extern Int GameMain();

int main(int argc, char **argv)
{
#if !defined(_WIN32)
	__argc = argc;
	__argv = argv;
#endif

	GgcFlags::DumpTableIfRequested();

	GGC_TRACE("main entered argc=%d", argc);

#if defined(_WIN32)
	ApplicationHInstance = GetModuleHandle(NULL);
#endif

	// TheSuperHackers @bugfix bobtista 30/04/2026 Build a Win32-style
	// command-line string from argv so GetCommandLineA() in the compat
	// shim returns the real arguments. The legacy parser expects token 0
	// to be the executable name and starts parsing at token 1, so argv[0]
	// must be preserved here.
	//
	// The engine's parseCommandLine tokenises with nextParam(buf, "\" "),
	// i.e. ' ' and '"' are the only separators and there is no backslash
	// escape - so we just wrap any arg that contains a space in double
	// quotes. Args that contain BOTH a space and a literal '"' are
	// unsupported by the engine parser itself, so we don't try to encode
	// them either.
	for (int i = 0; i < argc; ++i)
	{
		if (i > 0)
		{
			s_compatCommandLineStorage += ' ';
		}
		const char *a = argv[i];
		bool needsQuote = false;
		for (const char *p = a; *p != '\0'; ++p)
		{
			if (*p == ' ')
			{
				needsQuote = true;
				break;
			}
		}
		if (needsQuote)
		{
			s_compatCommandLineStorage += '"';
		}
		s_compatCommandLineStorage += a;
		if (needsQuote)
		{
			s_compatCommandLineStorage += '"';
		}
	}
	g_compatCommandLine = s_compatCommandLineStorage.c_str();

	// TheSuperHackers @bugfix bobtista 09/06/2026 WinMain initializes the debug log via
	// initMemoryManager(); the SDL3 entry point with the null memory manager never does, so a
	// logging build produced no output. Initialize it here so DEBUG_LOG reaches the log file and
	// console. Expands to nothing when debug logging is compiled out.
	DEBUG_INIT(DEBUG_FLAGS_DEFAULT);

	GGC_TRACE("calling SDL_Init");
	if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS))
	{
		SDL_Log("SDL_Init failed: %s", SDL_GetError());
		return 1;
	}
	GGC_TRACE("SDL_Init OK");

#if defined(__EMSCRIPTEN__)
	// TheSuperHackers @feature githubawn 29/07/2026 The browser's in-memory filesystem
	// is thrown away on reload, so options, saves and replays would never survive a
	// refresh. Mount IndexedDB (IDBFS) at /preferences and point the Unix user-data
	// lookup (GlobalData::BuildUserDataPathFromRegistry, XDG_DATA_HOME branch) at it,
	// which keeps the engine side unchanged. The initial syncfs(true) loads whatever
	// IndexedDB already holds; the interval flushes writes back out.
	setenv("XDG_DATA_HOME", "/preferences", 1);
	EM_ASM({
		FS.mkdir('/preferences');
		FS.mount(IDBFS, {}, '/preferences');
		FS.syncfs(true, function(err) {
			if (err) { console.error('IDBFS load failed:', err); }
		});
		setInterval(function() { FS.syncfs(false, function() {}); }, 5000);
	});

	// TheSuperHackers @feature githubawn 30/07/2026 Open the LAN relay socket now rather
	// than on the first UDP::Bind: the WebSocket handshake is asynchronous, so a bind
	// followed straight away by a LAN announce would send it before the socket was up and
	// lose it. The ?ip=N identity override is applied later, in
	// IPEnumeration::getAddresses, because a GlobalData re-init would clobber it here.
	ggc_ws_connect();
#endif

	int windowW = kDefaultWindowWidth;
	int windowH = kDefaultWindowHeight;
	bool wantWindowed = false;
	int requestedW = 0;
	int requestedH = 0;
	for (int argi = 1; argi < argc; ++argi)
	{
		if (strcmp(argv[argi], "-win") == 0)
		{
			wantWindowed = true;
		}
		else if (strcmp(argv[argi], "-xres") == 0 && argi + 1 < argc)
		{
			requestedW = atoi(argv[argi + 1]);
		}
		else if (strcmp(argv[argi], "-yres") == 0 && argi + 1 < argc)
		{
			requestedH = atoi(argv[argi + 1]);
		}
	}
#if defined(__EMSCRIPTEN__)
	// TheSuperHackers @bugfix 31/07/2026 Never ask for fullscreen on the web. The canvas is the
	// window here, and a browser only grants real fullscreen from a user gesture, so the request
	// did not produce a fullscreen page - it just sized the drawing buffer to the reported
	// desktop mode while the page kept presenting the canvas at its CSS box. The two disagreed,
	// so the cursor landed somewhere other than where it was drawn. Run windowed at the canvas'
	// own CSS size instead, which keeps the drawing buffer and the presented size in step.
	wantWindowed = true;
	if (requestedW <= 0 && requestedH <= 0)
	{
		double cssWidth = 0.0;
		double cssHeight = 0.0;
		if (emscripten_get_element_css_size("#canvas", &cssWidth, &cssHeight) == EMSCRIPTEN_RESULT_SUCCESS
			&& cssWidth >= 1.0 && cssHeight >= 1.0)
		{
			requestedW = (int)cssWidth;
			requestedH = (int)cssHeight;
		}
	}
#endif

	{
		const SDL_DisplayID primaryDisplay = SDL_GetPrimaryDisplay();
		const SDL_DisplayMode *desktopMode = SDL_GetDesktopDisplayMode(primaryDisplay);
		if (!wantWindowed && desktopMode != nullptr && desktopMode->w > 0 && desktopMode->h > 0)
		{
			windowW = desktopMode->w;
			windowH = desktopMode->h;
		}
	}

	// TheSuperHackers @bugfix bobtista 28/05/2026 Honor -xres/-yres when -win is set so '-win -xres 1600 -yres 1200' produces a 1600x1200 window instead of 800x600.
	if (wantWindowed)
	{
		if (requestedW > 0)
		{
			windowW = requestedW;
		}
		if (requestedH > 0)
		{
			windowH = requestedH;
		}
	}
	Uint32 windowFlags = SDL_WINDOW_RESIZABLE;
#if defined(__APPLE__)
	windowFlags |= SDL_WINDOW_METAL;
	// TheSuperHackers @bugfix bobtista 08/06/2026 Do NOT create the window hidden on macOS for
	// fullscreen. A real fullscreen Space (which hides the menu bar + Dock) is entered via
	// -[NSWindow toggleFullScreen:], and AppKit only animates a VISIBLE, active window into a Space;
	// toggling a hidden window degrades to a borderless window confined to the usable area. The
	// fullscreen transition below happens fast enough that there is no meaningful windowed flash.
#else
	// TheSuperHackers @bugfix bobtista 28/05/2026 Hide the window during fullscreen bring-up so it doesn't briefly appear at the requested resolution before SDL_SetWindowFullscreen takes effect; windowed runs show the window immediately.
	if (!wantWindowed)
	{
		windowFlags |= SDL_WINDOW_HIDDEN;
	}
#endif
	GGC_TRACE("calling SDL_CreateWindow");
	TheSDL3Window = SDL_CreateWindow(kWindowTitle, windowW, windowH, windowFlags);
	if (TheSDL3Window == NULL)
	{
		SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
		SDL_Quit();
		return 1;
	}
#if !defined(__APPLE__)
	if (!wantWindowed)
	{
		SDL_SetWindowFullscreenMode(TheSDL3Window, nullptr);
		SDL_SetWindowFullscreen(TheSDL3Window, true);
		SDL_SyncWindow(TheSDL3Window);
	}
#endif
	GGC_TRACE("SDL_CreateWindow OK window=%p", (void*)TheSDL3Window);

	// TheSuperHackers @feature bobtista 08/06/2026 Enforce a minimum content size so a drag
	// cannot shrink the window below what the fixed-resolution UI can lay out. SDL_SetWindowAspectRatio
	// is avoided: on macOS its windowWillResize: delegate traps AppKit's live-resize loop.
	SDL_SetWindowMinimumSize(TheSDL3Window, kMinWindowWidth, kMinWindowHeight);

	ApplicationHWnd = (HWND)TheSDL3Window;

#if defined(__APPLE__)
	// TheSuperHackers @bugfix bobtista 30/04/2026 Use SDL3's official
	// Metal-view helper so we own a CAMetalLayer-backed NSView and can
	// hand bgfx the CAMetalLayer directly. Without this, bgfx receives
	// the NSWindow and races with SDL3 for control of the contentView's
	// layer, which manifests as intermittent AGX driver compilation
	// crashes in AGCDeserializedReply on macOS Tahoe / Apple Silicon.
	GGC_TRACE("calling SDL_Metal_CreateView");
	TheSDL3MetalView = SDL_Metal_CreateView(TheSDL3Window);
	if (TheSDL3MetalView != NULL)
	{
		TheSDL3MetalLayer = SDL_Metal_GetLayer(TheSDL3MetalView);
		GGC_TRACE("SDL_Metal_CreateView OK view=%p layer=%p",
		          (void*)TheSDL3MetalView, TheSDL3MetalLayer);
	}
	else
	{
		SDL_Log("SDL_Metal_CreateView failed: %s", SDL_GetError());
	}

	// TheSuperHackers @bugfix bobtista 08/06/2026 Enter a REAL macOS fullscreen Space (hides the menu
	// bar + Dock, covers the whole display). Per SDL3's Cocoa backend this needs a resizable window
	// (set above), desktop/NULL fullscreen mode (so it is not "exclusive"), and the window VISIBLE and
	// raised when toggled - a window that is still hidden makes SDL_SetWindowFullscreen a no-op and
	// falls back to a borderless window confined to the usable area (menu bar + Dock left on top).
	if (!wantWindowed)
	{
		SDL_ShowWindow(TheSDL3Window);
		SDL_RaiseWindow(TheSDL3Window);
		SDL_SetWindowFullscreenMode(TheSDL3Window, nullptr);
		SDL_SetWindowFullscreen(TheSDL3Window, true);
		SDL_SyncWindow(TheSDL3Window);
	}
#endif

	// TheSuperHackers @build bobtista 30/04/2026 Mirror the early-init the
	// Win path does in WinMain.cpp: build TheVersion, then run command-line
	// parsing so TheWritableGlobalData exists before GameEngine::init runs.
	TheVersion = NEW Version;
	TheVersion->setVersion(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILDNUM, VERSION_LOCALBUILDNUM,
		AsciiString(VERSION_BUILDUSER), AsciiString(VERSION_BUILDLOC),
		AsciiString(__TIME__), AsciiString(__DATE__));

	GGC_TRACE("calling parseCommandLineForStartup cmdline='%s'", g_compatCommandLine);
	CommandLine::parseCommandLineForStartup();
	GGC_TRACE("parseCommandLineForStartup OK headless=%d",
	          (TheGlobalData != NULL && TheGlobalData->m_headless) ? 1 : 0);

	// TheSuperHackers @bugfix bobtista 30/04/2026 -headless asks for
	// engine-only execution (no rendering, no audio); on Apple Silicon
	// macOS Tahoe even initialising bgfx Metal trips the AGX driver
	// bug, so explicitly null out ApplicationHWnd here so the renderer
	// chain (W3DDisplay::init -> WW3D::Init -> DX8Wrapper::Init ->
	// BgfxBackend::Initialize) bails on null hwnd before any Metal
	// pipeline state is constructed.
	if (TheGlobalData != NULL && TheGlobalData->m_headless)
	{
		ApplicationHWnd = NULL;
	}

	// TheSuperHackers @fix bobtista 08/07/2026 Mirror WinMain: refuse to start a
	// second client instance. Multi-instance builds and command-line flags claim
	// a free instance slot inside initialize() instead of failing.
	Int result = 0;
	if (rts::ClientInstance::initialize())
	{
		GGC_TRACE("calling GameMain");
		result = GameMain();
		GGC_TRACE("GameMain returned result=%d", result);
	}
	else
	{
		DEBUG_LOG(("Generals is already running...Bail!"));
	}

#if defined(__APPLE__)
	if (TheSDL3MetalView != NULL)
	{
		SDL_Metal_DestroyView(TheSDL3MetalView);
		TheSDL3MetalView = NULL;
		TheSDL3MetalLayer = NULL;
	}
#endif

	SDL_DestroyWindow(TheSDL3Window);
	TheSDL3Window = NULL;
	ApplicationHWnd = NULL;
	SDL_Quit();

	return result;
}

#endif
