/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
*/

#if defined(SAGE_USE_SDL3)

// TheSuperHackers @build bobtista 29/04/2026 Pull in the Win compat shim
// before any engine header so AsciiString.h's inline _stricmp resolves
// (compat/win32_shims/windows.h maps it to strcasecmp on non-Win).
#include <windows.h>

#include <SDL3/SDL.h>
#include <string>

#include "Common/CommandLine.h"
#include "Common/Debug.h"
#include "Common/GameEngine.h"
#include "Common/GameMemory.h"
#include "Common/version.h"
#include "GameClient/ClientInstance.h"
#include "SDL3GameEngine.h"
// Version constants generated by cmake at configure time.
#include "BuildVersion.h"
#include "GeneratedVersion.h"

namespace
{
	const char * const kWindowTitle = "Command & Conquer Generals Zero Hour";
	const int kDefaultWindowWidth = 800;
	const int kDefaultWindowHeight = 600;
}

int __argc = 0;
char **__argv = NULL;

// TheSuperHackers @bugfix bobtista 30/04/2026 Backing storage for the
// compat shim's GetCommandLineA(). Populated in main() before any
// CommandLine::parse* call so the engine sees the real arg vector
// joined into a single Win32-style command-line string.
const char *g_compatCommandLine = "";
static std::string s_compatCommandLineStorage;

// TheSuperHackers @build bobtista 29/04/2026 Globals normally provided by the
// Win-side WinMain.cpp.
const char *g_strFile = "data/Generals.str";
const char *g_csfFile = "data/%s/Generals.csf";

// Stack-dump shims. The Win build provides these in core_debug; the engine
// references them from RTS_DEBUG / IG_DEBUG_STACKTRACE-gated code so just
// give them weak no-ops on non-Win.
#include "Common/StackDump.h"
AsciiString g_LastErrorDump;
void FillStackAddresses(void ** /*addresses*/, unsigned int /*count*/, unsigned int /*skip*/) {}
void StackDumpFromAddresses(void ** /*addresses*/, unsigned int /*count*/, void (* /*cb*/)(const char *)) {}
void StackDump(void (* /*cb*/)(const char *)) {}
void StackDumpFromContext(unsigned long /*eip*/, unsigned long /*esp*/, unsigned long /*ebp*/, void (* /*cb*/)(const char *)) {}
void GetFunctionDetails(void * /*p*/, char * /*name*/, char * /*filename*/, unsigned int * /*line*/, unsigned int * /*addr*/) {}
void DumpExceptionInfo(unsigned int /*u*/, EXCEPTION_POINTERS * /*e*/) {}

// OS busy-state UI is Win-only.
void OSDisplaySetBusyState(Bool /*busyDisplay*/, Bool /*busySystem*/) {}

SDL_Window *TheSDL3Window = NULL;
void *ApplicationHWnd = NULL;

extern Int GameMain();

int main(int argc, char **argv)
{
	__argc = argc;
	__argv = argv;

	// TheSuperHackers @bugfix bobtista 30/04/2026 Build a Win32-style
	// command-line string from argv so GetCommandLineA() in the compat
	// shim returns the real arguments. parseCommandLine tokenises by
	// whitespace and respects double quotes, so wrap any arg that
	// contains a space and escape embedded quotes.
	for (int i = 1; i < argc; ++i)
	{
		if (i > 1)
		{
			s_compatCommandLineStorage += ' ';
		}
		const char *a = argv[i];
		bool needsQuote = false;
		for (const char *p = a; *p != '\0'; ++p)
		{
			if (*p == ' ' || *p == '\t')
			{
				needsQuote = true;
				break;
			}
		}
		if (needsQuote)
		{
			s_compatCommandLineStorage += '"';
		}
		for (const char *p = a; *p != '\0'; ++p)
		{
			if (*p == '"')
			{
				s_compatCommandLineStorage += '\\';
			}
			s_compatCommandLineStorage += *p;
		}
		if (needsQuote)
		{
			s_compatCommandLineStorage += '"';
		}
	}
	g_compatCommandLine = s_compatCommandLineStorage.c_str();

	if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS))
	{
		SDL_Log("SDL_Init failed: %s", SDL_GetError());
		return 1;
	}

	Uint32 windowFlags = SDL_WINDOW_RESIZABLE;
#if defined(__APPLE__)
	windowFlags |= SDL_WINDOW_METAL;
#endif
	int windowW = kDefaultWindowWidth;
	int windowH = kDefaultWindowHeight;
	{
		const SDL_DisplayID primaryDisplay = SDL_GetPrimaryDisplay();
		const SDL_DisplayMode *desktopMode = SDL_GetDesktopDisplayMode(primaryDisplay);
		if (desktopMode != nullptr && desktopMode->w > 0 && desktopMode->h > 0)
		{
			windowW = desktopMode->w;
			windowH = desktopMode->h;
		}
	}
	bool wantWindowed = false;
	for (int argi = 1; argi < argc; ++argi)
	{
		if (strcmp(argv[argi], "-win") == 0)
		{
			wantWindowed = true;
			windowW = kDefaultWindowWidth;
			windowH = kDefaultWindowHeight;
			break;
		}
	}
	TheSDL3Window = SDL_CreateWindow(kWindowTitle, windowW, windowH, windowFlags);
	if (TheSDL3Window == NULL)
	{
		SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
		SDL_Quit();
		return 1;
	}
	if (!wantWindowed)
	{
		SDL_SetWindowFullscreenMode(TheSDL3Window, nullptr);
		SDL_SetWindowFullscreen(TheSDL3Window, true);
		SDL_SyncWindow(TheSDL3Window);
	}

	ApplicationHWnd = TheSDL3Window;

	// TheSuperHackers @build bobtista 30/04/2026 Mirror the early-init the
	// Win path does in WinMain.cpp: build TheVersion, then run command-line
	// parsing so TheWritableGlobalData exists before GameEngine::init runs.
	TheVersion = NEW Version;
	TheVersion->setVersion(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILDNUM, VERSION_LOCALBUILDNUM,
		AsciiString(VERSION_BUILDUSER), AsciiString(VERSION_BUILDLOC),
		AsciiString(__TIME__), AsciiString(__DATE__));

	CommandLine::parseCommandLineForStartup();

	// TheSuperHackers @fix bobtista 08/07/2026 Mirror WinMain: refuse to start a
	// second client instance. Multi-instance builds and command-line flags claim
	// a free instance slot inside initialize() instead of failing.
	Int result = 0;
	if (rts::ClientInstance::initialize())
	{
		result = GameMain();
	}
	else
	{
		DEBUG_LOG(("Generals is already running...Bail!"));
	}

	SDL_DestroyWindow(TheSDL3Window);
	TheSDL3Window = NULL;
	ApplicationHWnd = NULL;
	SDL_Quit();

	return result;
}

#endif
